apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: databases
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
   - group: '*'
     kind: '*'
  destinations:
   - namespace: '*'
     server: '*'
  sourceRepos:
   - '*'
