apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identidock
spec:
  destination:
    name: in-cluster
    namespace: webapps
  project: webapplications
  source:
    repoURL: https://github.com/hakobmkoyan771/testingInfra.git
    path: .
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
